### ISSUE TITLE
Status de uma submissão após o comando "rejulgar"

### ISSUE THREAD

**Issue by johngardenghi** [cd-moj/cdmoj#12]
Quando um problema de um contest é rejulgado, a resposta da submissão na página "Todas as Submissões" no contest não é integralmente atualizado. Veja, por exemplo, a submissão 1561414864:b80188cbc25443ed6741b476e48a912d nos printscreens abaixo.

![todas_as_submissoes](https://user-images.githubusercontent.com/9977591/60100678-9d9c4780-9730-11e9-97c0-69dd4c664a03.png)

![contest](https://user-images.githubusercontent.com/9977591/60100676-9d9c4780-9730-11e9-82c3-46db85b2c7fd.png)

**Comment by bcribas** [comment]
fixed
